import { Component } from '@angular/core';
import { NavController, NavParams, Platform, ModalController, ToastController, AlertController } from 'ionic-angular';
import { Auth, User } from '@ionic/cloud-angular';

//native functionality libraries
import { Facebook } from 'ionic-native';
//import { TwitterConnect } from 'ionic-native';
//import { Instagram } from 'ionic-native';

import { AboutPage } from '../about/about';

//Prototype modals for login page
//import { IgLoginPage } from '../iglogin/iglogin';
//import { FbLoginPage } from '../fblogin/fblogin';
//import { TwLoginPage } from '../twlogin/twlogin';

import { EmailLoginPage } from '../emaillogin/emaillogin';


@Component({
  selector: 'page-settings',
  templateUrl: 'settings.html'
})
export class SettingsPage {

  public dailyPush: boolean;

  public autoGenChecked: boolean;
  public autoGenDisabled: boolean;

  public toggleIcon: string;
  public toggleOpen: boolean;

  public fbLink: boolean;
  public igLink: boolean;
  public twLink: boolean;
  public emailLink: boolean;

  public FB_APP_ID: number = 1355955421093900;
  

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              public platform: Platform,
              public ModalCtrl: ModalController,
              public toastCtrl: ToastController,
              public alertCtrl: AlertController,
              public auth: Auth,
              public user: User
  ) {


    this.dailyPush = true;

    this.autoGenChecked = false;
    this.autoGenDisabled = false;

    this.toggleIcon = 'arrow-dropright';
    this.toggleOpen = false;

    this.igLink = false;
    this.fbLink = false;
    this.twLink = false;
    this.emailLink = false;
  

    //initialize Facebook SDK
    Facebook.browserInit(this.FB_APP_ID, 'v2.8');
    
  }
 

  //autogenerated Ionic 2 function
  ionViewDidLoad() {
    console.log('ionViewDidLoad SettingsPage');
  }

  
  // toggles daily push notifications
  togglePush(bool: boolean) {

    let myBool = bool;
    let vMessage: string = !myBool ? 'Don\'t forget to take a daily selfie for best results' : 'You will now receive a daily push to take a selfie';
    
    //create toast notification for toggling a push notification
    let toast = this.toastCtrl.create({
      message: vMessage,
      duration: 3000,
      position: 'bottom',
      showCloseButton: true,
      closeButtonText: 'close'
    });

    toast.present();


    //toggle off autogenerate if daily push is off
    if (!myBool) {
      this.autoGenChecked = false;
      this.toggleOpen = false;
      this.toggleIcon = 'arrow-dropright';
    }
    this.autoGenDisabled = !myBool;
    
  }


  //display About page
  showAbout() {

    let aboutModal = this.ModalCtrl.create(AboutPage);
    aboutModal.enableBack();
    aboutModal.present();
  }


  //access autogenerate features
  toggleAutoGen(myBool: boolean) {

    if (myBool === false) {
      this.autoGenChecked = false;
      this.toggleOpen = false;
    }
    else {
      this.autoGenChecked = !this.autoGenChecked;
    }

    if(this.autoGenChecked === false) {
      this.toggleOpen = false;
      this.toggleIcon = 'arrow-dropright';
    }

    console.log('autogenchecked: ' + this.autoGenChecked);
  }



  //displays autogenerate options
  toggleVisible() {

    if (this.autoGenChecked) {

      this.toggleOpen = !this.toggleOpen;

      this.toggleIcon = this.toggleOpen ? 'arrow-dropdown' : 'arrow-dropright';

    }
  }



  /****************/
  //INSTAGRAM LOGIN
  /****************/

  checkLoginIg() {
    
    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    if(this.igLink === false) {

      this.auth.login('instagram').then((response) => {

        let twToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Instagram account',
          duration: 3000,
          position: 'bottom'
        });
        twToast.present();
        
        //alert(JSON.stringify(response));

        this.igLink = !this.igLink;
      });
    } else {
      let igAlert = this.alertCtrl.create({

        title: 'Log out of Instagram',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.igLink = this.igLink;
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.igLink = !this.igLink;
    
              let igToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Instagram account',
                duration: 3000,
                position: 'bottom'
              });

              igToast.present();
            }
          }
        ] //end buttons
      });

      igAlert.present();
    }


    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.igLink === false) { //if user is not logged into instagram

      console.log('igLink is ' + this.igLink);

      let igModal = this.ModalCtrl.create(IgLoginPage);

      igModal.enableBack();

      igModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.igLink = this.igLink;
        } else { //login success

          this.igLink = !this.igLink; 
   
          let igToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Instagram account',
            duration: 3000,
            position: 'bottom'
          });
          igToast.present();
        }
        console.log('igLink after modal is ' + this.igLink);
      });

      igModal.present();

    } else {
      let igAlert = this.alertCtrl.create({

        title: 'Log out of Instagram',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.igLink = this.igLink;
              console.log('igLink after alert is ' + this.igLink);
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.igLink = !this.igLink;
    
              let igToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Instagram account',
                duration: 3000,
                position: 'bottom'
              });

              igToast.present();
         
              console.log('igLink after alert is ' + this.igLink);
              console.log('logged out of instagram');
            }
          }
        ] //end buttons
      });

      igAlert.present();
    }*/
    /****************/
    
  }

  


  /****************/
  //FACEBOOK LOGIN
  /****************/

  checkLoginFb() {
    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    /***
     *Throws InternalServiceError
     *'The Facebook access_token endpoint
     *had an error: This IP can't make
     *requests from that application' status 500
     ***/

    /*if (this.fbLink === false) {
      this.auth.login('facebook').then((response) => {

        this.fbLink = !this.fbLink;
        let fbToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Facebook account',
          duration: 3000,
          position: 'bottom'
        });
        fbToast.present();
      });

    } else {
      let fbAlert = this.alertCtrl.create({

        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.fbLink = !this.fbLink;
              let fbToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Facebook account',
                duration: 3000,
                position: 'bottom'
              });

              fbToast.present();

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }
        ] //end buttons
      });

      fbAlert.present();
    }*/
    /**************************/



    /***********************/
    //FACEBOOK NATIVE LOGIN
    /***********************/
    if(this.fbLink === false) {

      Facebook.login(['email']).then((response) => {
        if(response.authResponse) {
          this.fbLink = true;
          let fbToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Facebook account',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
        else {
          let fbToast = this.toastCtrl.create({
            message: 'User cancelled login or did not fully authorize',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
      });  
    } //end if

    else { //if fbLink === true
      let fbAlert = this.alertCtrl.create({
        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              Facebook.logout().then((response) => {
                this.fbLink = !this.fbLink;
                let fbToast = this.toastCtrl.create({
                  message: 'Lapse is no longer linked to your Facebook account',
                  duration: 3000,
                  position: 'bottom'
                });

                fbToast.present();
              });
              

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }] //end buttons
      });

      fbAlert.present();
    }
    /******************/
    

    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.fbLink === false) { //if user is not logged into facebook

      console.log('fbLink is ' + this.fbLink);

      let fbModal = this.ModalCtrl.create(FbLoginPage);

      fbModal.enableBack();

      fbModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.fbLink = this.fbLink;
        } else {

          this.fbLink = !this.fbLink;
          let fbToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Facebook account',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
        console.log('fbLink after modal is ' + this.fbLink);
      });

      fbModal.present();

    } else {
      let fbAlert = this.alertCtrl.create({

        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.fbLink = !this.fbLink;
              let fbToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Facebook account',
                duration: 3000,
                position: 'bottom'
              });

              fbToast.present();

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }
        ] //end buttons
      });

      fbAlert.present();
    }*/
    /**************/

  }



  /***************/
  //TWITTER LOGIN
  /***************/

  checkLoginTw() {

    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    if (this.twLink === false) {

      this.auth.login('twitter').then((response) => {

        let twToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Instagram account',
          duration: 3000,
          position: 'bottom'
        });

        twToast.present();

        this.twLink = !this.twLink;

      });

    } else {

      let twAlert = this.alertCtrl.create({
        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.twLink = !this.twLink;
              let twToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Twitter account',
                duration: 3000,
                position: 'bottom'
              });

              twToast.present();
              

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }
        ] //end buttons
      });

      twAlert.present();
    }
    /********************/


    /******************************/
    //FABRIC API - TWITTER CONNECT
    /******************************/
    /*if(this.twLink === false) {
      TwitterConnect.login().then((response) => {
        if (response.token) {
          this.twLink = !this.twLink;
          let twToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Twitter account',
            duration: 3000,
            position: 'bottom'
          });
          twToast.present();
        }

      }, (error) => {
        let twToast = this.toastCtrl.create({
          message: JSON.stringify(error),
          duration: 3000,
          position: 'bottom'
        });
        twToast.present();
      });

    } else { //if twLink = true
      let twAlert = this.alertCtrl.create({
        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              TwitterConnect.logout().then((response) => {
                this.twLink = !this.twLink;
                let twToast = this.toastCtrl.create({
                  message: 'Lapse is no longer linked to your Twitter account',
                  duration: 3000,
                  position: 'bottom'
                });

                twToast.present();
              });
              

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }] //end buttons
      });

      twAlert.present();
    }*/
    /******************/




    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.twLink === false) { //if user is not logged into twitter

      console.log('twLink is ' + this.twLink);

      let twModal = this.ModalCtrl.create(TwLoginPage);

      twModal.enableBack();

      twModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.twLink = this.twLink;
        } else {

          this.twLink = !this.twLink;
          let twToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Twitter account',
            duration: 3000,
            position: 'bottom'
          });
          twToast.present();
        }
        console.log('twLink after modal is ' + this.twLink);
      });

      twModal.present();

    } else {  //if user is logged in
      let twAlert = this.alertCtrl.create({

        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.twLink = !this.twLink;

              let twToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Twitter account',
                duration: 3000,
                position: 'bottom'
              });

              twToast.present();

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }
        ] //end buttons
      });

      twAlert.present();
    }*/
    //*************
  }




  checkLoginEmail() {

    /***************/
    //ORIGINAL MODAL
    /***************/
    if(this.emailLink === false) { //if user is not logged into an email

      console.log('emailLink is ' + this.emailLink);

      let emailModal = this.ModalCtrl.create(EmailLoginPage);

      emailModal.enableBack();

      emailModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.emailLink = this.emailLink;
        } else {

          this.emailLink = !this.emailLink;
          let emailToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your email account',
            duration: 3000,
            position: 'bottom'
          });
          emailToast.present();
        }
        console.log('emailLink after modal is ' + this.emailLink);
      });

      emailModal.present();

    } else {
      let emailAlert = this.alertCtrl.create({

        title: 'Log out of your email',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.emailLink = this.emailLink;
              console.log('emailLink after alert is ' + this.emailLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.emailLink = !this.emailLink;

              let emailToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your email account',
                duration: 3000,
                position: 'bottom'
              });

              emailToast.present();

              console.log('emailLink after alert is ' + this.emailLink);
              console.log('logged out of email');
            }
          }
        ] //end buttons
      });

      emailAlert.present();
    }
    /**************/
  }
}
