import { Component } from '@angular/core';
import { NavController, NavParams, Platform, ModalController, ToastController, AlertController } from 'ionic-angular';
import { Auth, User } from '@ionic/cloud-angular';

//native functionality libraries
import { Facebook } from 'ionic-native';
//import { TwitterConnect } from 'ionic-native';
//import { Instagram } from 'ionic-native';

import { AboutPage } from '../about/about';

//Prototype modals for login page
//import { IgLoginPage } from '../iglogin/iglogin';
//import { FbLoginPage } from '../fblogin/fblogin';
//import { TwLoginPage } from '../twlogin/twlogin';

import { EmailLoginPage } from '../emaillogin/emaillogin';


@Component({
  selector: 'page-settings',
  templateUrl: 'settings.html'
})
export class SettingsPage {

  //default toggle value
  public dailyPush: boolean;

  //default toggle values
  public autoGenChecked: boolean;
  public autoGenDisabled: boolean;

  //default extra options toggle values
  public toggleIcon: string;
  public toggleOpen: boolean;

  //default login statuses
  public fbLink: boolean;
  public igLink: boolean;
  public twLink: boolean;
  public emailLink: boolean;

  //facebook app id number
  public FB_APP_ID: number = 1355955421093900;
 
  //instagram login button attributes
  public igAuthIcon: string;
  public igAuthText: string;
  public igLoginColor: string;
  public iOutline: boolean;

  //facebook login button attributes
  public fbAuthIcon: string;
  public fbAuthText: string;
  public fbLoginColor: string;
  public fOutline: boolean;

  //twitter login button attributes
  public twAuthIcon: string;
  public twAuthText: string;
  public twLoginColor: string;
  public tOutline: boolean;

  //email login button attributes
  public emailAuthIcon: string;
  public emailAuthText: string;
  public emailLoginColor: string;
  public eOutline: boolean;

  //checkbox values
  public oneWeek: boolean;
  public twoWeek: boolean;
  public threeWeek: boolean;
  public fourWeek: boolean;
  public twoMonth: boolean;
  public threeMonth: boolean;
  public fourMonth: boolean;
  public sixMonth: boolean;
  

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              public platform: Platform,
              public ModalCtrl: ModalController,
              public toastCtrl: ToastController,
              public alertCtrl: AlertController,
              public auth: Auth,
              public user: User
  ) {


    this.dailyPush = true;

    this.autoGenChecked = false;
    this.autoGenDisabled = false;

    this.toggleOpen = false;

    this.updateToggleIcon();
    this.igLink = false;
    this.fbLink = false;
    this.twLink = false;
    this.emailLink = false;

    this.oneWeek = false;
    this.twoWeek = false;
    this.threeWeek = false;
    this.fourWeek = false;
    this.twoMonth = false;
    this.threeMonth = false;
    this.fourMonth = false;
    this.sixMonth = false;
  
    this.updateButtons('instagram');
    this.updateButtons('facebook');
    this.updateButtons('twitter');
    this.updateButtons('email');

    //initialize Facebook SDK
    Facebook.browserInit(this.FB_APP_ID, 'v2.8');
    
  }
 

  //autogenerated Ionic 2 function
  ionViewDidLoad() {
    console.log('ionViewDidLoad SettingsPage');
  }

  
  // toggles daily push notifications
  togglePush() {

    this.dailyPush = !this.dailyPush;
    this.autoGenDisabled = this.dailyPush ? false : true;

    if (this.dailyPush === false) {

      this.autoGenChecked = false;
      this.autoGenDisabled = true;
      this.toggleOpen = false;
      this.updateToggleIcon(); 
    }

    //declare 2 alternate toast strings
    let toastText: string = !this.dailyPush ? 'Don\'t forget to take a daily selfie for best results' : 'You will now receive a daily push to take a selfie';
    
    //create toast notification for toggling a push notification
    this.toastCtrl.create({
      message: toastText,
      duration: 3000,
      position: 'bottom',
      showCloseButton: true,
      closeButtonText: 'close'
    }).present();   
  }


  //display About page
  showAbout() {

    let aboutModal = this.ModalCtrl.create(AboutPage);
    aboutModal.enableBack();
    aboutModal.present();
  }


  //access autogenerate features
  toggleAutoGen() {

    if (this.dailyPush === false) {                 //disable autoGen and close toggleOpen
      this.autoGenChecked = false;
      this.autoGenDisabled = true;
      this.toggleOpen = false;
      this.updateToggleIcon();
    }
    else {   //if dailyPush is on
      this.autoGenChecked = !this.autoGenChecked;   //toggle autoGen

      if(this.autoGenChecked === false) {           //toggle toggleOpen, update toggleIcon
        this.toggleOpen = false;
        this.updateToggleIcon();
      }
    }
  }



  //displays autogenerate options
  toggleVisible() {

    if (this.autoGenChecked) {
      this.toggleOpen = !this.toggleOpen;
      this.updateToggleIcon();
    }
  }


  //toggles dropdown arrow
  updateToggleIcon() {
    this.toggleIcon = this.toggleOpen ? 'arrow-dropdown-circle' : 'arrow-dropright-circle';
  }

  toggle(months: number) {   //stores AutoGen boolean checkbox values 

    switch(months) {
      case 2: {
        this.twoMonth = !this.twoMonth;
        break;
      }
      case 3: {
        this.threeMonth = !this.threeMonth;
        break;
      }
      case 4: {
        this.fourMonth = !this.fourMonth;
        break;
      }
      case 6: {
        this.sixMonth = !this.sixMonth;
        break;
      }
      case 7: {
        this.oneWeek = !this.oneWeek;
        break;
      }
      case 14: {
        this.twoWeek = !this.twoWeek;
        break;
      }
      case 21: {
        this.threeWeek = !this.threeWeek;
        break;
      }
      case 28: {
        this.fourWeek = !this.fourWeek;
        break;
      }
      default: {
        console.log('nothing happened');
        break;
      }
    }
  }




  updateButtons(social: string) {

    switch(social) {
      case 'instagram': {
        this.igAuthIcon = this.igLink ? 'checkmark-circle' : 'alert';
        this.igAuthText = this.igLink ? 'logged in' : 'not logged in';
        this.igLoginColor= this.igLink ? 'dark' : 'light';
        this.iOutline = false; //this.igLink ? false : true;
        break;
      } 
      case 'facebook': {
        this.fbAuthIcon = this.fbLink ? 'checkmark-circle' : 'alert';
        this.fbAuthText = this.fbLink ? 'logged in' : 'not logged in';
        this.fbLoginColor= this.fbLink ? 'dark' : 'light';
        this.fOutline = false; // this.fbLink ? false : true;
        break;
      } 
      case 'twitter': {
        this.twAuthIcon = this.twLink ? 'checkmark-circle' : 'alert';
        this.twAuthText = this.twLink ? 'logged in' : 'not logged in';
        this.twLoginColor= this.twLink ? 'dark' : 'light';
        this.tOutline = false; // this.twLink ? false : true;
        break;
      } 
      case 'email': {
        this.emailAuthIcon = this.emailLink ? 'checkmark-circle' : 'alert';
        this.emailAuthText = this.emailLink ? 'logged in' : 'not logged in';
        this.emailLoginColor= this.emailLink ? 'dark' : 'light';
        this.eOutline = false; // this.emailLink ? false : true;
        break;
      }
      default: {
        console.log('nothing happened');
        break;
      }
    }
  }


  /****************/
  //INSTAGRAM LOGIN
  /****************/

  checkLoginIg() {
    
    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    if(this.igLink === false) {

      this.auth.login('instagram').then((response) => {

        let twToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Instagram account',
          duration: 3000,
          position: 'bottom'
        });
        twToast.present();
        
        //alert(JSON.stringify(response));

        this.igLink = !this.igLink;
        this.updateButtons('instagram');
      });
    } else { //if user is logged in

      let igAlert = this.alertCtrl.create({

        title: 'Log out of Instagram',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.igLink = this.igLink;
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.igLink = !this.igLink;
              this.updateButtons('instagram');
    
              let igToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Instagram account',
                duration: 3000,
                position: 'bottom'
              });

              igToast.present();
            }
          }
        ] //end buttons
      });

      igAlert.present();
    }


    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.igLink === false) { //if user is not logged into instagram

      let igModal = this.ModalCtrl.create(IgLoginPage);

      igModal.enableBack();

      igModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.igLink = this.igLink;
        } else { //login success

          this.igLink = !this.igLink; 
          this.updateButtons('instagram');
   
          let igToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Instagram account',
            duration: 3000,
            position: 'bottom'
          });
          igToast.present();
        }
        console.log('igLink after modal is ' + this.igLink);
      });

      igModal.present();

    } else {
      let igAlert = this.alertCtrl.create({

        title: 'Log out of Instagram',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {

              this.igLink = this.igLink;

            }
          }, {
            text: 'Log out',
            handler: () => {

              this.igLink = !this.igLink;
              this.updateButtons('instagram');
              let igToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Instagram account',
                duration: 3000,
                position: 'bottom'
              });

              igToast.present();
            }
          }
        ] //end buttons
      });

      igAlert.present();
    }*/
    /****************/
    
  }

  


  /****************/
  //FACEBOOK LOGIN
  /****************/

  checkLoginFb() {
    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    /***
     *Throws InternalServiceError
     *'The Facebook access_token endpoint
     *had an error: This IP can't make
     *requests from that application' status 500
     ***/

    /*if (this.fbLink === false) {
      this.auth.login('facebook').then((response) => {

        this.fbLink = !this.fbLink;
        this.updateButtons('facebook');
        let fbToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Facebook account',
          duration: 3000,
          position: 'bottom'
        });
        fbToast.present();
      });

    } else {
      let fbAlert = this.alertCtrl.create({

        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.fbLink = !this.fbLink;
              this.updateButtons('facebook');
              let fbToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Facebook account',
                duration: 3000,
                position: 'bottom'
              });

              fbToast.present();

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }
        ] //end buttons
      });

      fbAlert.present();
    }*/
    /****END CLOUD AUTH FACEBOOK LOGIN****/



    /***********************/
    //FACEBOOK NATIVE LOGIN
    /***********************/
    if(this.fbLink === false) {

      Facebook.login(['email']).then((response) => {
        if(response.authResponse) {
          this.fbLink = !this.fbLink;
          this.updateButtons('facebook');
          let fbToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Facebook account',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
        else {
          let fbToast = this.toastCtrl.create({
            message: 'User cancelled login or did not fully authorize',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
      });  
    } //end if

    else { //if fbLink === true
      let fbAlert = this.alertCtrl.create({
        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              Facebook.logout().then((response) => {
                this.fbLink = !this.fbLink;
                this.updateButtons('facebook');
                let fbToast = this.toastCtrl.create({
                  message: 'Lapse is no longer linked to your Facebook account',
                  duration: 3000,
                  position: 'bottom'
                });

                fbToast.present();
              });
              

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }] //end buttons
      });

      fbAlert.present();
    }
    /********END NATIVE FACEBOOK LOGIN**********/
    

    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.fbLink === false) { //if user is not logged into facebook

      console.log('fbLink is ' + this.fbLink);

      let fbModal = this.ModalCtrl.create(FbLoginPage);

      fbModal.enableBack();

      fbModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.fbLink = this.fbLink;
        } else {

          this.fbLink = !this.fbLink;
          this.updateButtons('facebook');
          let fbToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Facebook account',
            duration: 3000,
            position: 'bottom'
          });
          fbToast.present();
        }
        console.log('fbLink after modal is ' + this.fbLink);
      });

      fbModal.present();

    } else {
      let fbAlert = this.alertCtrl.create({

        title: 'Log out of Facebook',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.fbLink = this.fbLink;
              console.log('fbLink after alert is ' + this.fbLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.fbLink = !this.fbLink;
              this.updateButtons('facebook');
              let fbToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Facebook account',
                duration: 3000,
                position: 'bottom'
              });

              fbToast.present();

              console.log('fbLink after alert is ' + this.fbLink);
              console.log('logged out of facebook');
            }
          }
        ] //end buttons
      });

      fbAlert.present();
    }*/
    /*******END ORIGINAL MODAL*******/

  }



  /***************/
  //TWITTER LOGIN
  /***************/

  checkLoginTw() {

    /**************************/
    //CLOUD ANGULAR AUTH LOGIN
    /**************************/
    if (this.twLink === false) {

      this.auth.login('twitter').then((response) => {

        let twToast = this.toastCtrl.create({
          message: 'Lapse is now linked to your Instagram account',
          duration: 3000,
          position: 'bottom'
        });

        twToast.present();

        this.twLink = !this.twLink;
        this.updateButtons('twitter');

      });

    } else {

      let twAlert = this.alertCtrl.create({
        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.auth.logout();
              this.twLink = !this.twLink;
              this.updateButtons('twitter');
              let twToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Twitter account',
                duration: 3000,
                position: 'bottom'
              });

              twToast.present();
              

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }
        ] //end buttons
      });

      twAlert.present();
    }
    /********************/


    /******************************/
    //FABRIC API - TWITTER CONNECT
    /******************************/
    /*if(this.twLink === false) {
      TwitterConnect.login().then((response) => {
        if (response.token) {
          this.twLink = !this.twLink;
          this.updateButtons('twitter');
          let twToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Twitter account',
            duration: 3000,
            position: 'bottom'
          });
          twToast.present();
        }

      }, (error) => {
        let twToast = this.toastCtrl.create({
          message: JSON.stringify(error),
          duration: 3000,
          position: 'bottom'
        });
        twToast.present();
      });

    } else { //if twLink = true
      let twAlert = this.alertCtrl.create({
        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',
        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              TwitterConnect.logout().then((response) => {
                this.twLink = !this.twLink;
                this.updateButtons('twitter');
                let twToast = this.toastCtrl.create({
                  message: 'Lapse is no longer linked to your Twitter account',
                  duration: 3000,
                  position: 'bottom'
                });

                twToast.present();
              });
              

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }] //end buttons
      });

      twAlert.present();
    }*/
    /******************/




    /***************/
    //ORIGINAL MODAL
    /***************/
    /*if(this.twLink === false) { //if user is not logged into twitter

      console.log('twLink is ' + this.twLink);

      let twModal = this.ModalCtrl.create(TwLoginPage);

      twModal.enableBack();

      twModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.twLink = this.twLink;
        } else {

          this.twLink = !this.twLink;
          this.updateButtons('twitter');
          let twToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your Twitter account',
            duration: 3000,
            position: 'bottom'
          });
          twToast.present();
        }
        console.log('twLink after modal is ' + this.twLink);
      });

      twModal.present();

    } else {  //if user is logged in
      let twAlert = this.alertCtrl.create({

        title: 'Log out of Twitter',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.twLink = this.twLink;
              console.log('twLink after alert is ' + this.twLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.twLink = !this.twLink;
              this.updateButtons('email');

              let twToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your Twitter account',
                duration: 3000,
                position: 'bottom'
              });

              twToast.present();

              console.log('twLink after alert is ' + this.twLink);
              console.log('logged out of twitter');
            }
          }
        ] //end buttons
      });

      twAlert.present();
    }*/
    //*************
  }




  checkLoginEmail() {

    /***************/
    //ORIGINAL MODAL
    /***************/
    if(this.emailLink === false) { //if user is not logged into an email

      console.log('emailLink is ' + this.emailLink);

      let emailModal = this.ModalCtrl.create(EmailLoginPage);

      emailModal.enableBack();

      emailModal.onDidDismiss(data => {
        if (data === 'cancel') {
          this.emailLink = this.emailLink;
        } else {

          this.emailLink = !this.emailLink;
          this.updateButtons('email');
          let emailToast = this.toastCtrl.create({
            message: 'Lapse is now linked to your email account',
            duration: 3000,
            position: 'bottom'
          });
          emailToast.present();
        }
        console.log('emailLink after modal is ' + this.emailLink);
      });

      emailModal.present();

    } else {
      let emailAlert = this.alertCtrl.create({

        title: 'Log out of your email',
        message: 'Are you sure you want to logout?',

        buttons: [
          {
            text: 'Cancel',
            role: 'cancel',
            handler: () => {
              this.emailLink = this.emailLink;
              console.log('emailLink after alert is ' + this.emailLink)
              console.log('cancel');
            }
          }, {
            text: 'Log out',
            handler: () => {
              this.emailLink = !this.emailLink;
              this.updateButtons('email');

              let emailToast = this.toastCtrl.create({
                message: 'Lapse is no longer linked to your email account',
                duration: 3000,
                position: 'bottom'
              });

              emailToast.present();

              console.log('emailLink after alert is ' + this.emailLink);
              console.log('logged out of email');
            }
          }
        ] //end buttons
      });

      emailAlert.present();
    }
    /**************/
  }
}
